Changed check module

diff --git a/src/commands/check-namings.yml b/src/commands/check-namings.yml
--- a/src/commands/check-namings.yml
+++ b/src/commands/check-namings.yml
@@ -9,9 +9,9 @@ steps:
   -run:
     name: Check module name
     command: |
-      if ! echo "<< parameters.module_name >>" | grep -q '^[a-z0-9][a-z0-9-]*[a-z0-9]$'
+      if ! echo << parameters.module_name >> | grep -q '^[a-z0-9][a-z0-9-]*[a-z0-9]$'
       then
-        echo "module_name: \"<< parameters.module_name >>\" is not valid." 1>2
-        echo "module_name must be all lowercase letters, numbers and the \"-\" symbol. It cannot start or end with \"-\"." 1>&2
+        echo "module_name: \"<< parameters.module_name >>\" is not valid."
+        echo "module_name must be all lowercase letters, numbers and the \"-\" symbol. It cannot start or end with \"-\"."
         exit 1
       fi
